In [1]:
import pandas as pd
import numpy as np

In [2]:
df528 = pd.read_csv("content/empdata.csv")

df528.head()

,Empid,Ename,Salary,DOJ
0,1001,Ganesh,1000.00,10-10-2000
1,1002,Anil,23000.50,3/20/2002
2,1003,Gaurav,NaN,03-03-2002
3,1004,Hema Chandra,16500.50,09-10-2000
4,1005,Laxmi Prasanna,12000.75,10-08-2000


In [3]:
df528.tail(2)

,Empid,Ename,Salary,DOJ
4,1005,Laxmi Prasanna,12000.75,10-08-2000
5,1006,Anant,9999.99,09-09-1999


In [4]:
df528.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Empid   6 non-null      int64  
 1   Ename   6 non-null      object 
 2   Salary  5 non-null      float64
 3   DOJ     6 non-null      object 
dtypes: float64(1), int64(1), object(2)
memory usage: 324.0+ bytes


In [5]:
df528.describe()

,Empid,Salary
count,6.000000,5.000000
mean,1003.500000,12500.348000
std,1.870829,8139.622234
min,1001.000000,1000.000000
25%,1002.250000,9999.990000
50%,1003.500000,12000.750000
75%,1004.750000,16500.500000
max,1006.000000,23000.500000


In [6]:
df528.shape

(6, 4)

In [7]:
type(df528)

pandas.core.frame.DataFrame

In [8]:
df528.columns

Index(['Empid', 'Ename', 'Salary', 'DOJ'], dtype='object')

In [9]:
df528.Empid

0    1001
1    1002
2    1003
3    1004
4    1005
5    1006
Name: Empid, dtype: int64

In [10]:
df528[['Empid','Ename']]

,Empid,Ename
0,1001,Ganesh
1,1002,Anil
2,1003,Gaurav
3,1004,Hema Chandra
4,1005,Laxmi Prasanna
5,1006,Anant


In [11]:
df528_1 = pd.concat([df528, df528])
print('Dimensions of the original frame:', df528_1.shape)
print('Dimensions of the frame with duplicates:', df528_1.shape)

df528_1 = df528_1.drop_duplicates()
print('Dimensions of the frame after removing duplicates:', df528_1.shape)

Dimensions of the original frame: (12, 4)
Dimensions of the frame with duplicates: (12, 4)
Dimensions of the frame after removing duplicates: (6, 4)


In [12]:
df528.columns = [i.upper() for i in df528]
print(df528.columns)

Index(['EMPID', 'ENAME', 'SALARY', 'DOJ'], dtype='object')


In [13]:
df528.isna().sum()

EMPID     0
ENAME     0
SALARY    1
DOJ       0
dtype: int64

In [14]:
print('Highest salary is', df528['SALARY'].max())
print('Lowest salary is', df528['SALARY'].min())

Highest salary is 23000.5
Lowest salary is 1000.0


In [15]:
df528[df528.SALARY > 20000]

,EMPID,ENAME,SALARY,DOJ
1,1002,Anil,23000.5,3/20/2002


In [16]:
df528[['EMPID', 'ENAME']] [df528.SALARY > 20000]

,EMPID,ENAME
1,1002,Anil


In [17]:
df528[['EMPID','ENAME']] [df528.SALARY == df528.SALARY.max()]

,EMPID,ENAME
1,1002,Anil


In [18]:
print('Average salary is', df528.SALARY.mean())
df528['ENAME'][df528.SALARY > df528.SALARY.mean()]

Average salary is 12500.348


1            Anil
3    Hema Chandra
Name: ENAME, dtype: object

In [19]:
df528_1['DOJ'] = pd.to_datetime(df528_1['DOJ'], format='mixed')
df528_1.info()
print('Frame before sorting\n', df528_1)
df528_1.sort_values("DOJ", inplace = True)
print('Frame after sorting\n', df528_1)

<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype         
---  ------  --------------  -----         
 0   Empid   6 non-null      int64         
 1   Ename   6 non-null      object        
 2   Salary  5 non-null      float64       
 3   DOJ     6 non-null      datetime64[ns]
dtypes: datetime64[ns](1), float64(1), int64(1), object(1)
memory usage: 240.0+ bytes
Frame before sorting
    Empid           Ename    Salary        DOJ
0   1001          Ganesh   1000.00 2000-10-10
1   1002            Anil  23000.50 2002-03-20
2   1003          Gaurav       NaN 2002-03-03
3   1004    Hema Chandra  16500.50 2000-09-10
4   1005  Laxmi Prasanna  12000.75 2000-10-08
5   1006          Anant    9999.99 1999-09-09
Frame after sorting
    Empid           Ename    Salary        DOJ
5   1006          Anant    9999.99 1999-09-09
3   1004    Hema Chandra  16500.50 2000-09-10
4   1005  Laxmi Prasanna  12000.75 2000-10-08
0   10

In [20]:
df528_1.sort_values("DOJ", ascending = False, inplace = True)
df528_1

,Empid,Ename,Salary,DOJ
1,1002,Anil,23000.50,2002-03-20
2,1003,Gaurav,NaN,2002-03-03
0,1001,Ganesh,1000.00,2000-10-10
4,1005,Laxmi Prasanna,12000.75,2000-10-08
3,1004,Hema Chandra,16500.50,2000-09-10
5,1006,Anant,9999.99,1999-09-09


In [21]:
df528_1.sort_values(by = ['DOJ', 'Salary'], ascending = [False, True], inplace = True)
df528_1

,Empid,Ename,Salary,DOJ
1,1002,Anil,23000.50,2002-03-20
2,1003,Gaurav,NaN,2002-03-03
0,1001,Ganesh,1000.00,2000-10-10
4,1005,Laxmi Prasanna,12000.75,2000-10-08
3,1004,Hema Chandra,16500.50,2000-09-10
5,1006,Anant,9999.99,1999-09-09


In [22]:
a528 = np.array([1, 2, 3])
print(type(a528), a528.shape, a528[0], a528[1], a528[2])

<class 'numpy.ndarray'> (3,) 1 2 3


In [23]:
a528[0] = 5
print(a528)

[5 2 3]


In [24]:
b528 = np.array([[1,2],[3,4]])
print(b528)

[[1 2]
 [3 4]]


In [25]:
print(b528.shape)

(2, 2)


In [26]:
a528 = np.zeros((2,2))
print(a528)

[[0. 0.]
 [0. 0.]]


In [27]:
b528 = np.ones((1,2))
print(b528)

[[1. 1.]]


In [28]:
c528 = np.full((2,2), 7)
print(c528)

[[7 7]
 [7 7]]


In [29]:
d528 = np.eye(2)
print(d528)

[[1. 0.]
 [0. 1.]]


In [30]:
e528 = np.random.random((2,2))
print(e528)

[[0.94120949 0.98838983]
 [0.98994811 0.10548415]]


In [31]:
f528 = np.arange(10,50,5)
print(f528)

[10 15 20 25 30 35 40 45]


In [32]:
g528 = np.linspace(0., 1., num=5)
print(g528)

[0.   0.25 0.5  0.75 1.  ]


In [33]:
a528 = np.array([1, 2, 3])
b528 = np.array([4, 5, 6])
np.vstack((a528, b528))

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
a528 = np.array([[7], [8], [9]])
b528 = np.array([[4], [5], [6]])
np.hstack((a528, b528))

array([[7, 4],
       [8, 5],
       [9, 6]])

In [35]:
a528 = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

b528 = a528[:2, 1:3]
print(b528)

[[2 3]
 [6 7]]


In [36]:
x528 = np.array([1, 2])
y528 = np.array([1.0, 2.0])
z528 = np.array([1, 2], dtype=np.int64)
print(x528.dtype, y528.dtype, z528.dtype)

int32 float64 int64


In [37]:
%%time
x528 = 0
for element in a528:
    x528 = x528 + element

CPU times: total: 0 ns
Wall time: 0 ns


In [38]:
x528 = np.array([[1,2],[3,4]], dtype=np.float64)
y528 = np.array([[5,6],[7,8]], dtype=np.float64)
print(x528 + y528)
print(np.add(x528, y528))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [39]:
print(x528 - y528)
print(np.subtract(x528, y528))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [40]:
print(x528 * y528)
print(np.multiply(x528, y528))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [41]:
print(x528 / y528)
print(np.divide(x528, y528))

print(np.sqrt(x528))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [42]:
x528 = np.array([[1, 2], [3, 4], [5, 6]])
print(np.max(x528))
print(np.min(x528))
print(np.sum(x528))

6
1
21


In [43]:
x528 = np.array([[1, 2], [5, 3], [4, 6]])
print(np.max(x528, axis=0))
print(np.max(x528, axis=1))

[5 6]
[2 5 6]


In [44]:
x528 = np.array([[1, 2], [3, 4], [5, 6]])
print(x528)
print("Transpose\n", x528.T)

[[1 2]
 [3 4]
 [5 6]]
Transpose
 [[1 3 5]
 [2 4 6]]


In [45]:
v528 = np.array([[1,2,3]])
print(v528)
print("Transpose\n", v528.T)

[[1 2 3]]
Transpose
 [[1]
 [2]
 [3]]


In [46]:
w528 = np.array([[1],[2],[3]])
print(w528)
w528.shape

[[1]
 [2]
 [3]]


(3, 1)

In [47]:
y528 = w528.reshape(-1,)
print(y528)
y528.shape

[1 2 3]


(3,)